skin: midnight
title: econoalchemist
description: A blog focused on Bitcoin self custody & censorship resistance.
author: econoalchemist<i class="fad fa-home-lg"></i>
avatar: /logo.png
email: econoalchemist@protonmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter: 
  username: econoalchemist
  card: summary
logo: logo.png
social:
  name:
  links:
    - https://twitter.com/econoalchemist
    - https://github.com/econoalchemist
    - https://t.me/econoalchemist
lang: en
